# Generated by Django 5.0 on 2024-01-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emp_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(max_length=100),
        ),
    ]
