# Generated by Django 5.0 on 2024-01-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emp_app", "0003_alter_employee_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="role",
            old_name="name",
            new_name="role",
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(max_length=100),
        ),
    ]
